# Generated by Django 3.0.5 on 2020-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200418_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defaultProfileImg.png', null=True, upload_to='_profile_img'),
        ),
    ]
