# Generated by Django 3.0.5 on 2020-04-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('manufacture', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=50)),
                ('onSale', models.BooleanField(blank=True, default=True)),
                ('image1', models.ImageField(default='defaultProfileImg.png', upload_to='_profile_img')),
                ('image2', models.ImageField(blank=True, default='defaultProfileImg.png', null=True, upload_to='_profile_img')),
                ('image3', models.ImageField(blank=True, default='defaultProfileImg.png', null=True, upload_to='_profile_img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
