# Generated by Django 3.0.5 on 2020-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200502_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='products',
        ),
        migrations.AddField(
            model_name='comments',
            name='description',
            field=models.CharField(default=22, max_length=120),
            preserve_default=False,
        ),
    ]
