# Generated by Django 3.0.5 on 2020-04-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
